# Configuración de Clippy
# Solo configuraciones específicas que son reconocidas por Clippy

# Umbral de complejidad cognitiva (reemplaza cyclomatic-complexity-threshold)
cognitive-complexity-threshold = 20

# Umbral de parámetros de función
too-many-arguments-threshold = 7

# Umbral de líneas de código
too-many-lines-threshold = 100
