name: PHP Coverage

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  coverage:
    name: Run tests and generate coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug
          extensions: pdo, json, mbstring, xml
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader

      - name: Run tests with coverage
        run: |
          mkdir -p build/logs
          XDEBUG_MODE=coverage ./vendor/bin/phpunit --configuration phpunit-sqlite.xml --coverage-clover build/logs/clover.xml --testdox || true

      - name: Parse clover and upload results
        run: |
          if [ -f build/logs/clover.xml ]; then
            php .github/scripts/parse-clover.php build/logs/clover.xml 70 > build/logs/coverage-summary.txt || true
          else
            echo "No clover found" > build/logs/coverage-summary.txt
          fi

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: php-coverage-report
          path: |
            build/logs/clover.xml
            build/logs/coverage-summary.txt
          retention-days: 7
